const groupActionTypes = {
    GET_GROUPS_START: "GET_GROUPS_START",
    GET_GROUPS_SUCCESS: "GET_GROUPS_SUCCESS",
    GET_GROUPS_FAILURE: "GET_GROUPS_FAILURE",
    CREATE_GROUP_START: "CREATE_GROUP_START",
    CREATE_GROUP_SUCCESS: "CREATE_GROUP_SUCCESS",
    CREATE_GROUP_FAILURE: "CREATE_GROUP_FAILURE",
    DELETE_GROUP_START: "DELETE_GROUP_START",
    DELETE_GROUP_SUCCESS: "DELETE_GROUP_SUCCESS",
    DELETE_GROUP_FAILURE: "DELETE_GROUP_FAILURE",
    ADD_USER_START: "ADD_USER_START",
    ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
    ADD_USER_FAILURE: "ADD_USER_FAILURE",
    GET_USERS_IN_GROUP_START: "GET_USERS_IN_GROUP_START",
    GET_USERS_IN_GROUP_SUCCESS: "GET_USERS_IN_GROUP_SUCCESS",
    GET_MESSAGES_OF_GROUP_START: "GET_MESSAGES_OF_GROUP_START",
    GET_MESSAGES_OF_GROUP_SUCCESS: "GET_MESSAGES_OF_GROUP_SUCCESS",
    ADD_MESSAGE_TO_STORE: "ADD_MESSAGE_TO_STORE",
    ADD_NEW_MESSAGE_START: 'ADD_NEW_MESSAGE_START',
    ADD_NEW_MESSAGE_SUCCESS: 'ADD_NEW_MESSAGE_SUCCESS',
    JOIN_ROOM_START: 'JOIN_ROOM_START'
};

export default groupActionTypes;
