const groupActionTypes = {
    GET_GROUPS_START: "GET_GROUPS_START",
    GET_GROUPS_SUCCESS: "GET_GROUPS_SUCCESS",
    GET_GROUPS_FAILURE: "GET_GROUPS_FAILURE",
    CREATE_GROUP_START: "CREATE_GROUP_START",
    CREATE_GROUP_SUCCESS: "CREATE_GROUP_SUCCESS",
    CREATE_GROUP_FAILURE: "CREATE_GROUP_FAILURE",
    DELETE_GROUP_START: "DELETE_GROUP_START",
    DELETE_GROUP_SUCCESS: "DELETE_GROUP_SUCCESS",
    DELETE_GROUP_FAILURE: "DELETE_GROUP_FAILURE",
    ADD_USER_START: "ADD_USER_START",
    ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
    ADD_USER_FAILURE: "ADD_USER_FAILURE",
    GET_USERS_IN_GROUP_START: "GET_USERS_IN_GROUP_START",
    GET_USERS_IN_GROUP_SUCCESS: "GET_USERS_IN_GROUP_SUCCESS"
};

export default groupActionTypes;
