const groupActionTypes = {
    GET_GROUPS_START: "GET_GROUPS_START",
    GET_GROUPS_SUCCESS: "GET_GROUPS_SUCCESS",
    GET_GROUPS_FAILURE: "GET_GROUPS_FAILURE",
    CREATE_GROUP_START: "CREATE_GROUP_START",
    CREATE_GROUP_SUCCESS: "CREATE_GROUP_SUCCESS",
    CREATE_GROUP_FAILURE: "CREATE_GROUP_FAILURE"
};

export default groupActionTypes;
