const userActionTypes = {
    SET_CURRENT_USER: "SET_CURRENT_USER",
    SIGN_IN_START: "SIGN_IN_START",
    SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
    SIGN_IN_FAILURE: "SIGN_IN_FAILURE",
    SIGN_OUT_START: "SIGN_OUT_START",
    SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
    SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE",
    SIGN_UP_START: "SIGN_UP_START",
    SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
    SIGN_UP_FAILURE: "SIGN_UP_FAILURE",
    UPLOAD_PROFILE_START: "UPLOAD_PROFILE_START",
    UPLOAD_PROFILE_SUCCESS: "UPLOAD_PROFILE_SUCCESS",
    UPLOAD_PROFILE_FAILURE: "UPLOAD_PROFILE_FAILURE",
    UPLOAD_COVER_START: "UPLOAD_COVER_START",
    UPLOAD_COVER_SUCCESS: "UPLOAD_COVER_SUCCESS",
    UPLOAD_COVER_FAILURE: "UPLOAD_COVER_FAILURE",
};

export default userActionTypes;
